### ISSUE TITLE
Unequal hashes produced by server and local machine

### ISSUE THREAD

**Issue by dertrockx** [starkfire/QSHS-Project-Arachnid#10]
I tried replicating your hashing algorithm (i.e. sha512(password + salt)). But when I tried doing it on my local machine (both in php and in python), I produce a different result. 
Example:
```python
# in python
import hashlib
password = 'Password123'
salt = 'f34a4be289513ca2bf36f8d7db249156e85ff212f093632941e3afbb9d5fca04888d4b132a666910e0495864965ba874dd1f657078691a5b6ca92ee5c32f1662'
hashlib.sha512().update(password + salt).hexdigest()
# produces '29218a458c004c9266b2d858e21cfad1d275e0c992f22e186a44864c61e87ac12a15ab99eec98d59b04bf2eae57addd596b3dac0addc0e081ca03b6194faed75'
```
```php
<?php
$password = 'Password123'
$salt = 'f34a4be289513ca2bf36f8d7db249156e85ff212f093632941e3afbb9d5fca04888d4b132a666910e0495864965ba874dd1f657078691a5b6ca92ee5c32f1662'
echo hash('sha512', $password . $salt);
// still produces '29218a458c004c9266b2d858e21cfad1d275e0c992f22e186a44864c61e87ac12a15ab99eec98d59b04bf2eae57addd596b3dac0addc0e081ca03b6194faed75'
?>
```
but in the server, it produced 'a282e79ac05f5abdb2cb3cb47a4b965d09c8be65f8230f0479b4e7eb4409fac870a35e7b851df461bfa36cc2efbaeb177625c5b224b327f26a17d73876df3da8' 
EDIT:
sorry for my ungrammatical ways

**Comment by rivenirvana** [comment]
Is it 100% replicated? Including language and library versions?

**Comment by dertrockx** [comment]
do you mean, there's a possibility that the issue may be caused by, idk different php versions?

**Comment by rivenirvana** [comment]
It would be wise to check, just to be sure. This definitely is weird behavior if it was 100% replicated.

**Comment by dertrockx** [comment]
i forgot to mention, the project was running on my machine when I generated that password hash i.e. when I created a test account

**Comment by rivenirvana** [comment]
Ahh. Duly noted. In that case, I'm afraid I don't have an idea on what the issue might be.

**Comment by dertrockx** [comment]
@starkfire

**Comment by rivenirvana** [comment]
Should I label this now as "Won't fix"?

**Comment by dertrockx** [comment]
**FIX**: Finally, I was able to replicate the hashing process of the server.
**REASON OF PROBLEM**: before the **signup.php** sends the password data to **registration_handler.php**, the **form_handler.js** first handles the data POSTed by the user (obviously, for security purposes). But I found out that that at **function formVerify()**, the password is hashed using sha512 before it sends the data.
```javascript
var h = document.createElement("input");
    form.appendChild(h);
    h.name = "h";
    h.type = "hidden";
    
    h.value = hex_sha512(password.value); // <---------------------- here's the problem; password is hashed
   // ...
    form.submit();   // <------------------ here, the form is submitted
    return true;
```
Then, when  the server receives the data, it hashes the *hashed password* with the randomly generated salt.
